### ISSUE TITLE
DB issue.

### ISSUE THREAD

**Issue by irushad** [jackjoe/mailgun_logger#11]
I have issue in downloading logs to db despite new trigger. I see success message "Run triggered successfully. Data should be coming in"... So far no data in the db.

Best Regards,

21:09:22.511 [info] GET /events
21:09:22.516 [info] Sent 200 in 5ms
21:09:24.271 [info] GET /events
21:09:24.279 [info] Sent 200 in 8ms
21:09:25.118 [info] GET /
21:09:25.122 [info] Sent 200 in 3ms
21:09:26.874 [info] POST /trigger_run
21:09:26.877 [info] Sent 302 in 2ms
21:09:26.895 [info] GET /
21:09:26.898 [info] Sent 200 in 2ms
21:09:30.212 [info] GET /events
21:09:30.218 [info] Sent 200 in 6ms
21:11:54.871 [error] Task #PID<0.17811.0> started from #PID<0.17810.0> terminating
** (MyXQL.Error) (1406) Data too long for column 'message_subject' at row 1
    (ecto_sql 3.6.1) lib/ecto/adapters/myxql.ex:270: Ecto.Adapters.MyXQL.insert/6
    (ecto 3.6.1) lib/ecto/repo/schema.ex:717: Ecto.Repo.Schema.apply/4
    (ecto 3.6.1) lib/ecto/repo/schema.ex:342: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto 3.6.1) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
    (elixir 1.11.0) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.6.1) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:1005: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.0) lib/db_connection.ex:1512: DBConnection.run_transaction/4
Function: #Function<2.19295648/0 in MailgunLogger.run/0>
    Args: []
21:53:25.518 [info] GET /events
21:53:25.522 [info] Sent 200 in 3ms
21:54:12.898 [info] GET /
21:54:12.903 [info] Sent 200 in 4ms
21:54:15.396 [info] GET /events
21:54:15.401 [info] Sent 200 in 5ms
21:54:18.495 [info] GET /
21:54:18.499 [info] Sent 200 in 4ms
21:54:20.209 [info] POST /trigger_run
21:54:20.210 [info] Sent 302 in 1ms
21:54:20.222 [info] GET /
21:54:20.224 [info] Sent 200 in 1ms
21:57:20.211 [error] Task #PID<0.19744.0> started from #PID<0.19743.0> terminating
** (stop) exited in: Task.await(%Task{owner: #PID<0.19744.0>, pid: #PID<0.19745.0>, ref: #Reference<0.2477322715.1366294529.219296>}, 180000)
    ** (EXIT) time out
    (elixir 1.11.0) lib/task.ex:643: Task.await/2
    (elixir 1.11.0) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (mailgun_logger 0.2.0) lib/mailgun_logger.ex:27: MailgunLogger.run/0
    (elixir 1.11.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &MailgunLogger.run/0
    Args: []
21:58:47.518 [info] GET /events
21:58:47.520 [info] Sent 200 in 1ms

**Comment by jeroenbourgois** [comment]
@irushad as you can see in the log, there is an error inserting the message subject in the db:

> `** (MyXQL.Error) (1406) Data too long for column 'message_subject' at row 1`

Try updating your database table schema to increase the length for that column.

**Comment by irushad** [comment]
Thanks for your reply. Now I see below error regarding a time out.


Function: #Function<2.19295648/0 in MailgunLogger.run/0>,
    Args: [],
19:01:44.614 [info] POST /trigger_run,
19:01:44.616 [info] Sent 302 in 2ms,
19:01:44.622 [info] GET /,
19:01:44.625 [info] Sent 200 in 2ms,
19:01:47.227 [info] GET /,
19:01:47.230 [info] Sent 200 in 3ms,
19:01:48.206 [info] GET /events,
19:01:48.211 [info] Sent 200 in 4ms,
19:01:49.763 [info] GET /events,
19:01:49.768 [info] Sent 200 in 4ms,
19:01:50.343 [info] GET /,
19:01:50.345 [info] Sent 200 in 2ms,
19:01:52.686 [info] POST /trigger_run,
19:01:52.694 [info] Sent 302 in 8ms,
19:01:52.705 [info] GET /,
19:01:52.716 [info] Sent 200 in 11ms,
19:02:23.081 [info] GET /events,
19:02:23.082 [info] Sent 200 in 1ms,
19:02:24.858 [info] GET /events,
19:02:24.863 [info] Sent 200 in 5ms,
19:0erations/5,
    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:1005: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4,
    (db_connection 2.4.0) lib/db_connection.ex:1512: DBConnection.run_transaction/4,
Function: #Function<2.19295648/0 in MailgunLogger.run/0>,
    Args: [],
19:04:52.701 [error] Task #PID<0.3895.2> started from #PID<0.3894.2> terminating,
** (stop) exited in: Task.await(%Task{owner: #PID<0.3895.2>, pid: #PID<0.3896.2>, ref: #Reference<0.2477322715.1367343105.222009>}, 180000),
    ** (EXIT) time out,
    (elixir 1.11.0) lib/task.ex:643: Task.await/2,
    (elixir 1.11.0) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2,
    (mailgun_logger 0.2.0) lib/mailgun_logger.ex:27: MailgunLogger.run/0,
    (elixir 1.11.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2,
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3,
Function: &MailgunLogger.run/0,
    Args: [],
19:04:52.706 [info] MyXQL.Connection (#PID<0.3258.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.3896.2> exited,
19:06:22.720 [info] GET /events,
19:06:22.724 [info] Sent 200 in 3ms,
19:06:24.625 [info] GET /,
19:06:24.636 [info] Sent 200 in 10ms,
19:06:26.384 [info] POST /trigger_run,
19:06:26.386 [info] Sent 302 in 1ms,
19:06:26.393 [info] GET /,
19:06:26.397 [info] Sent 200 in 3ms,
19:09:26.387 [error] Task #PID<0.4356.2> started from #PID<0.4355.2> terminating,
** (stop) exited in: Task.await(%Task{owner: #PID<0.4356.2>, pid: #PID<0.4357.2>, ref: #Reference<0.2477322715.1367605249.17303>}, 180000),
    ** (EXIT) time out,
    (elixir 1.11.0) lib/task.ex:643: Task.await/2,
    (elixir 1.11.0) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2,
    (mailgun_logger 0.2.0) lib/mailgun_logger.ex:27: MailgunLogger.run/0,
    (elixir 1.11.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2,
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3,
Function: &MailgunLogger.run/0,
    Args: [],
19:09:26.391 [info] MyXQL.Connection (#PID<0.3260.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4357.2> exited,
19:11:22.481 [info] GET /events,
19:11:22.490 [info] Sent 200 in 8ms,
19:11:24.033 [info] GET /accounts,
19:11:24.039 [info] Sent 200 in 5ms,
19:11:30.301 [info] GET /,
19:11:30.303 [info] Sent 200 in 2ms,
19:11:32.502 [info] POST /trigger_run,
19:11:32.504 [info] Sent 302 in 1ms,
19:11:32.515 [info] GET /,
19:11:32.519 [info] Sent 200 in 4ms,
19:14:21.375 [info] GET /events,
19:14:21.380 [info] Sent 200 in 4ms,
19:14:27.953 [info] GET /accounts,
19:14:27.954 [info] Sent 200 in 1ms,
19:14:29.419 [info] GET /events,
19:14:29.422 [info] Sent 200 in 3ms,
19:14:30.853 [info] GET /,
19:14:30.905 [info] Sent 200 in 52ms,
19:14:32.506 [error] Task #PID<0.4707.2> started from #PID<0.4706.2> terminating,
** (stop) exited in: Task.await(%Task{owner: #PID<0.4707.2>, pid: #PID<0.4708.2>, ref: #Reference<0.2477322715.1367605249.95414>}, 180000),
    ** (EXIT) time out,
    (elixir 1.11.0) lib/task.ex:643: Task.await/2,
    (elixir 1.11.0) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2,
    (mailgun_logger 0.2.0) lib/mailgun_logger.ex:27: MailgunLogger.run/0,
    (elixir 1.11.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2,
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3,
Function: &MailgunLogger.run/0,
    Args: [],
19:14:32.517 [info] MyXQL.Connection (#PID<0.3258.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4708.2> exited,

**Comment by jeroenbourgois** [comment]
@irushad that is strange, we never had timeouts on our side, it has been running in production for months. BTW: could you format the log output? Just wrap it in backticks (see Github markdown docs).

Does your Mailgun account have many messages to pull on average?

**Comment by jeroenbourgois** [comment]
Closing due to inactivity.
