### ISSUE TITLE
Manual Trigger run on docker container based mailgun_logger

### ISSUE THREAD

**Issue by m3techitopsadmin** [jackjoe/mailgun_logger#20]
> 13:56:14.410 [error] Task #PID<0.4911.0> started from #PID<0.4909.0> terminating
> ** (Protocol.UndefinedError) protocol Enumerable not implemented for {:error, 502, "Bad Gateway"} of type Tuple. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Pager.Page, Range, Scrivener.Page, Stream
>     (elixir 1.13.1) lib/enum.ex:1: Enumerable.impl_for!/1
>     (elixir 1.13.1) lib/enum.ex:143: Enumerable.reduce/3
>     (elixir 1.13.1) lib/enum.ex:4144: Enum.map/2
>     (mailgun_logger 2202.4.3) lib/mailgun_logger/events/events.ex:112: MailgunLogger.Events.save_events/2
>     (mailgun_logger 2202.4.3) lib/mailgun_logger.ex:44: MailgunLogger.process_account/1
>     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
>     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
>     (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
> Function: #Function<2.78929076/0 in MailgunLogger.run/0>
>     Args: []

Hi, getting this error when clicking on trigger new run.

**Comment by jeroenbourgois** [comment]
This might have been an outage on the Mailgun side (see the 502 / Bad Gateway). Not sure what we can do here. Can you try again? I can trigger new runs here just fine. There will be a new release with some minor fixes, be sure to update.

**Comment by m3techitopsadmin** [comment]
Hi,

I deleted everything and started from scratch. Using the docker image. 

> 18:41:52.998 [error] Task #PID<0.3805.0> started from #PID<0.3804.0> terminating
> ** (stop) exited in: Task.await(%Task{owner: #PID<0.3805.0>, pid: #PID<0.3806.0>, ref: #Reference<0.3196055067.26279937.29196>}, 180000)
>     ** (EXIT) time out
>     (elixir 1.13.1) lib/task.ex:809: Task.await/2
>     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
>     (mailgun_logger 2202.4.4) lib/mailgun_logger.ex:27: MailgunLogger.run/0
>     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
>     (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
> Function: &MailgunLogger.run/0
>     Args: []
> 18:41:53.013 [info] MyXQL.Connection (#PID<0.3421.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.3806.0> exited

Not sure this is related to this error.

**Comment by jeroenbourgois** [comment]
@m3techitopsadmin sorry... do you have more info on the exact steps you followed? Can you try using the docker compose sample in the readme? Here is what I did and it is running just fine:

- create a `docker-compose.yml` file in `/tmp/mailgun_logger_test` with the content of the readme
- run `docker-compose up`

After some time, the app is started, migrations are ran and I can navigate to `http://0.0.0.0:5050/setup`...

**Comment by jeroenbourgois** [comment]
@m3techitopsadmin sorry, I'm gonna close this due to inactivity. Feel free to reply later on.
