### ISSUE TITLE
Docker startup fails because of missing S3 aws configuration (store_messages is on)

### ISSUE THREAD

**Issue by gdav** [jackjoe/mailgun_logger#26]
Hello,
I tried to run the docker compose setup, but it fails.
If I understand the message right, **store_messages** should be set to **off**,
otherwise, I need to configure an AWS S3 bucket.
(According README.MD)

I did not find any information how to set these configs from outside by docker environment vars.
If I check the code, it looks like, store_messages will not been read from ENV vars.

Maybe the docker-compose has a missing part, 
besides the postgres typo issues POSTGRES_ instead of POSTGRESS_

```
mailgun_logger-web-1  | |> MIGRATE_AND_SEED
mailgun_logger-web-1  | |> Starting dependencies...
mailgun_logger-web-1  | |> Starting repos...
mailgun_logger-web-1  | |> Running seed script...
mailgun_logger-web-1  | 13:21:30.110 [info] Migrations already up
mailgun_logger-web-1  | |> Success!
mailgun_logger-web-1  | 13:21:36.777 [notice] Application mailgun_logger exited: exited in: MailgunLogger.Application.start(:normal, [])
mailgun_logger-web-1  |     ** (EXIT) an exception was raised:
mailgun_logger-web-1  |         ** (RuntimeError) If `store_messages` is on, you need to configure ex_aws
mailgun_logger-web-1  |             (mailgun_logger 2308.1.1) lib/mailgun_logger/application.ex:33: MailgunLogger.Application.check_store_raw/0
mailgun_logger-web-1  |             (mailgun_logger 2308.1.1) lib/mailgun_logger/application.ex:9: MailgunLogger.Application.start/2
mailgun_logger-web-1  |             (kernel 8.5.4.1) application_master.erl:293: :application_master.start_it_old/4
mailgun_logger-web-1  | {"Kernel pid terminated",application_controller,"{application_start_failure,mailgun_logger,{bad_return,{{'Elixir.MailgunLogger.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => 
mailgun_logger-web-1  | <<\"If `store_messages` is on, you n
mailgun_logger-web-1  | eed to configure ex_aws\">>},[{'Elixir.MailgunLogger.Application',check_store_raw,0,[{file,\"lib/mailgun_logger/application.ex\"},{line,33},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.MailgunLogger.Application',start,2,[{file,\"lib/mailgun_logger/application.ex\"},{line,9}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}"}
mailgun_logger-web-1  | Kernel pid terminated (application_controller) ({application_start_failure,mailgun_logger,{bad_return,{{'Elixir.MailgunLogger.Applica
mailgun_logger-web-1  | tion',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"If `store_messages` is on, you need to configure ex_aws">>},[{'Elixir.MailgunLogger.Application',check_store_raw,0,[{file,"lib/mailgun_logger/application.ex"},{line,33},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.MailgunLogger.Application',start,2,[{file,"lib/mailgun_logger/application.ex"},{line,9}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}}})
mailgun_logger-web-1  | 
mailgun_logger-web-1  | Crash dump is being written to: erl_crash.dump...
mailgun_logger-web-1  | done
mailgun_logger-web-1 exited with code 1
```

**Comment by jeroenbourgois** [comment]
@gdav sry for the slow response. Indeed, the docker-compose file is a bit outdated. I'll try and have a look soon if you still need it?

**Comment by jeroenbourgois** [comment]
@dashart-ke can you try again? I just updated the Readme
